### ISSUE TITLE
Решал задачу?

### ISSUE THREAD

**Issue by Erixonich** [Dembl/JavaEdu#1]
Если, что не ясно, то спрашивай

**Comment by Dembl** [comment]
Да, не понял как делается все в методе get, пробовал много вариантов, но работал только этот, но как я понял это не правильно, так же есть вопросы по поводу удаления элемента, если можете, подскажите как можно это сделать? А так же когда вы будете свободны для занятия?

**Comment by Erixonich** [comment]
Добрался до компьютера.
Внимательно изучи коммит, так же переименовал пару классов, на это не обращай пока внимания. Я специально использовал наивную реализацию копирования массива в 
remove(), твоя задача переделать с использованием функций в Arrays.*
Жду решения **сегодня**

**Comment by Dembl** [comment]
Ну я вроде как сделал , но у меня получается он копирует т=массив только до удаляемого элемента, нужно ли сделать так, чтоб он так же копировал после удаленного элемента и потом запихивал в общий массив?
